apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-server
  template:
    metadata:
      labels:
        app: central-server
    spec:
      containers:
        - name: central-server
          image: central-server:latest
          ports:
            - containerPort: 5000
