apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-node
  template:
    metadata:
      labels:
        app: client-node
    spec:
      containers:
        - name: client-node
          image: client-node:latest
          ports:
            - containerPort: 5001
